language: rust

matrix:
  include:
    - rust: stable
    - rust: 1.38.0
    - rust: nightly
      script:
        - cd "${TRAVIS_BUILD_DIR}/big_enum_set"
        - cargo test
        - cargo test --features=serde
        - cargo test --features=nightly
        - cargo test --features=serde,nightly

script:
  - cd "${TRAVIS_BUILD_DIR}/big_enum_set"
  - cargo test
  - cargo test --features=serde
