[package]
name = "big_enum_set"
version = "0.1.0"
authors = ["Manu Thambi <manu@meshcapital.com>", "Lymia Aluysia <lymia@lymiahugs.com>"]
edition = "2018"

description = "A library for creating sets of enums with a large number of variants."
keywords = ["enum", "bitset", "set"]
categories = ["data-structures"]

documentation = "https://docs.rs/big_enum_set/"
repository = "https://github.com/manuthambi/big_enum_set"
readme = "../README.md"

license = "MIT/Apache-2.0"

[features]
nightly = ["big_enum_set_derive/nightly"]
serde = ["serde2", "big_enum_set_derive/serde"]

[dependencies]
big_enum_set_derive = { version = "0.1.0", path = "../big_enum_set_derive" }
num-traits = { version = "0.2", default-features = false }
serde2 = { package = "serde", version = "1.0.91", default-features = false, optional = true }

[dev-dependencies]
bincode = { version = "1.0", features = ["i128"] }
serde_derive = "1.0.91"
serde_json = "1.0.39"
